### ISSUE TITLE
Install SimDota2 in windows

### ISSUE THREAD

**Issue by huyrua291996** [lenLRX/SimDota2#3]
Hi,
Can you guide me step by step to install module in windows 10
I just clone this repo and test by import SimDota2 in python but i cant import
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\ML\dota 2\SimDota2\__init__.py", line 1, in <module>
    from .cppSimulator import *
ImportError: No module named 'SimDota2.cppSimulator'`

**Comment by lenLRX** [comment]
use SXS branch and compile with cmake.
make sure you got cppSimulator.pyd at the same level as CMakeLists.txt

**Comment by huyrua291996** [comment]
thanks
